# Generated by Django 4.1 on 2022-08-10 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_game_request_user'),
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_joiner', to='game.game'),
        ),
    ]
