# Generated by Django 4.1 on 2022-08-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_alter_joinrequest_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinrequest',
            old_name='created',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
