# Generated by Django 4.1 on 2022-08-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='title',
            new_name='sport_type',
        ),
    ]
