# Generated by Django 4.1 on 2022-08-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_title_game_sport_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_status',
        ),
        migrations.AddField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
