# Generated by Django 4.1 on 2022-08-09 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0007_alter_game_arranger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_joined',
            field=models.ManyToManyField(related_name='joined_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
