# Generated by Django 4.1 on 2022-08-09 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0008_alter_game_player_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='request_user',
            field=models.ManyToManyField(related_name='request_joined_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
